### ISSUE TITLE
Installation Fails

### ISSUE THREAD

**Issue by quavoce** [jbags81/fabric-home-assistant#33]
Fresh install of 2016-09-23-raspbian-jessie-lite.img on a Raspberry Pi 3

Initially tried wget but it failed with a TLS error:
pi@raspberrypi:~ $ wget -Nnv https://raw.githubusercontent.com/home-assistant/fabric-home-assistant/master/hass_rpi_installer.sh && bash hass_rpi_installer.sh
GnuTLS: A TLS fatal alert has been received.
GnuTLS: received alert [0]: Close notify
Unable to establish SSL connection.

Manually downloaded hass_rpi_installer.sh and then ran it from ~/

Installation progress including failure shown in pastebin log:

http://pastebin.com/Rg94t0wV

**Comment by aetjansen** [comment]
I seem to have the same issue when I tried it on both the latest versions of Jessie (both with Pixel and Lite). Those are the versions from 2016-11-25.

I did a fresh install of rasbian, expanded filesystem, used raspi-config to enable ssh, set timezone and changed default password for user pi.

then ran the installer and on both version of Jessie got this output:
http://hastebin.com/eqeviwelam.coffeescript

**Comment by aetjansen** [comment]
Will try to get a hold of older version of raspbian jessie to see which one did work. All links to zips on the raspberry pi website are not functioning atm though. For others who want to give it a try, here is a link to older images: http://downloads.raspberrypi.org/raspbian/images/ 

But, currently your best bet is to download the old torrent, since the zips dont actually download anything atm.

**Comment by aetjansen** [comment]
did a few quick tries on older versions of Jessie, to see if it fails because of changes in Jessie between versions, but I get the same result back to the version of 2016-05-10. Since bruh's video on the AIO installer is made on jun 18 (thats the date you see when he logs in on his pi), my guess is that it does not fail because of changes in Jessie, but something in the installer.
Hope this helps.

**Comment by DJ-Q** [comment]
I am also getting this error on a pi3 fresh Jessie install

**Comment by CodeWiesel** [comment]
[Those steps fixed that for me](https://community.home-assistant.io/t/one-timer-installer-fails-on-raspberry-pi-3/7470/9?u=codeweasel)

**Comment by patchedsoul** [comment]
root issue was due to aged pip and inability to build dependencies as a result. resolved in latest fixes.
